modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT License"
logoFile="he_addon-logo.png"
authors="_BENDY659_"
credits="Small boobs :("

[[mods]]
    modId = "he_addon"
    version = "${file.jarVersion}"
    displayName = "HollowEngine | ADDON"
    description = '''
    HollowEngine | ADDON - ths special addon for mod 'HollowEngine' by 'HollowHorizon'
    '''
[[dependencies.he_addon]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.6,44.0.0)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.he_addon]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.19.3)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.he_addon]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[3.12.0,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.he_addon]]
    modId="hollowengine"
    mandatory=true
    versionRange="[1.5.4,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.he_addon]]
    modId="hc"
    mandatory=true
    versionRange="[1.6.2,)"
    ordering = "NONE"
    side = "BOTH"